AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: ttec-connect-app Vanity Number Generator using TypeScript

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs22.x
    LoggingConfig:
      LogFormat: JSON

Resources:
  RSConnectVanityTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RSConnectVanityTable
      AttributeDefinitions:
        - AttributeName: CallerId
          AttributeType: S
      KeySchema:
        - AttributeName: CallerId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  VanityLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/index.handler
      Environment:
        Variables:
          DB_TABLE: !Ref RSConnectVanityTable
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref RSConnectVanityTable

  ConnectInstance:
    Type: AWS::Connect::Instance
    Properties:
      IdentityManagementType: CONNECT_MANAGED
      InstanceAlias: robs-connect-inbound-instance
      Attributes:
        InboundCalls: true
        OutboundCalls: false
        AutoResolveBestVoices: true
        ContactflowLogs: true

  ConnectContactFlow:
    Type: AWS::Connect::ContactFlow
    Properties:
      InstanceArn: !GetAtt ConnectInstance.Arn
      Name: InboundContactFlow
      Type: CONTACT_FLOW
      Content: |
        {
          "Version": "2019-10-30",
          "StartAction": "StartAction-999",
          "Metadata": {
            "Annotations": [],
            "name": "RS Demo Flow",
            "description": "For the proj",
            "type": "contactFlow"
          },
          "Actions": [
            {
              "Parameters": {},
              "Identifier": "DisconnectParticipant-999",
              "Type": "DisconnectParticipant",
              "Transitions": {}
            },
            {
              "Parameters": {
                "Text": "Something happened but its not us its you. Way to go."
              },
              "Identifier": "MessageParticipant-999",
              "Type": "MessageParticipant",
              "Transitions": {
                "NextAction": "DisconnectParticipant-999",
                "Errors": [
                  {
                    "NextAction": "DisconnectParticipant-999",
                    "ErrorType": "NoMatchingError"
                  }
                ]
              }
            },
            {
              "Parameters": {
                "Text": "We got 'em. Nice."
              },
              "Identifier": "MessageParticipant-111",
              "Type": "MessageParticipant",
              "Transitions": {
                "NextAction": "DisconnectParticipant-999",
                "Errors": [
                  {
                    "NextAction": "DisconnectParticipant-999",
                    "ErrorType": "NoMatchingError"
                  }
                ]
              }
            },
            {
              "Parameters": {
                "Text": "Heyoh! We be checking those digits. Thanks."
              },
              "Identifier": "StartAction-999",
              "Type": "MessageParticipant",
              "Transitions": {
                "NextAction": "InvokeLambdaFunction-007",
                "Errors": [
                  {
                    "NextAction": "InvokeLambdaFunction-007",
                    "ErrorType": "NoMatchingError"
                  }
                ]
              }
            },
            {
              "Parameters": {
                "LambdaFunctionARN": "arn:aws:lambda:us-east-1:182796259395:function:ttec-vanity-connect-app-VanityLambda-jwj4B5AxIibW",
                "InvocationTimeLimitSeconds": "3",
                "LambdaInvocationAttributes": {},
                "ResponseValidation": {
                  "ResponseType": "STRING_MAP"
                }
              },
              "Identifier": "InvokeLambdaFunction-007",
              "Type": "InvokeLambdaFunction",
              "Transitions": {
                "NextAction": "MessageParticipant-111",
                "Errors": [
                  {
                    "NextAction": "MessageParticipant-999",
                    "ErrorType": "NoMatchingError"
                  }
                ]
              }
            }
          ]
        }
      Description: Inbound call contact flow created by SAM

  ConnectLambdaAssociation:
    Type: AWS::Connect::IntegrationAssociation
    Properties:
      InstanceId: !Ref ConnectInstance
      IntegrationType: LAMBDA_FUNCTION
      IntegrationArn: !GetAtt VanityLambda.Arn

Outputs:
  ConnectInstanceId:
    Description: The Connect Instance ID
    Value: !Ref ConnectInstance

  ConnectInstanceArn:
    Description: The Connect Instance ARN
    Value: !GetAtt ConnectInstance.Arn

  ContactFlowId:
    Description: The Contact Flow ID
    Value: !Ref ConnectContactFlow

  VanityLambdaArn:
    Description: 'ARN of the Vanity Lambda'
    Value: !GetAtt VanityLambda.Arn
