AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: ttec-connect-app Vanity Number Generator using TypeScript

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs22.x
    LoggingConfig:
      LogFormat: JSON

Resources:
  RSConnectVanityTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RSConnectVanityTable
      AttributeDefinitions:
        - AttributeName: CallerId
          AttributeType: S
      KeySchema:
        - AttributeName: CallerId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  VanityLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/index.handler
      Environment:
        Variables:
          DB_TABLE: !Ref RSConnectVanityTable
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref RSConnectVanityTable

  ConnectInstance:
    Type: AWS::Connect::Instance
    Properties:
      IdentityManagementType: CONNECT_MANAGED
      InstanceAlias: robs-connect-inbound-instance
      Attributes:
        InboundCalls: true
        OutboundCalls: false
        AutoResolveBestVoices: true
        ContactflowLogs: true

  ConnectContactFlow:
    Type: AWS::Connect::ContactFlow
    Properties:
      InstanceArn: !GetAtt ConnectInstance.Arn
      Name: InboundContactFlow
      Type: CONTACT_FLOW
      Content: |
        {
          "Version": "2019-10-30",
          "StartAction": "e95d60c0-e95e-4f86-9904-0639dcc39f2b",
          "Metadata": {
            "entryPointPosition": {
              "x": 40,
              "y": 40
            },
            "Annotations": [],
            "name": "RS Demo Flow",
            "description": "Connect flow exercise.",
            "type": "contactFlow",
            "hash": {}
          },
          "Actions": [
            {
              "Parameters": {},
              "Identifier": "387a1596-3931-498c-a403-7667fb4cb927",
              "Type": "DisconnectParticipant",
              "Transitions": {}
            },
            {
              "Parameters": {
                "Text": "Something happened but its not us, its you."
              },
              "Identifier": "a26c7a4d-f42f-43b8-a394-8f74c82ba0b1",
              "Type": "MessageParticipant",
              "Transitions": {
                "NextAction": "387a1596-3931-498c-a403-7667fb4cb927",
                "Errors": [
                  {
                    "NextAction": "387a1596-3931-498c-a403-7667fb4cb927",
                    "ErrorType": "NoMatchingError"
                  }
                ]
              }
            },
            {
              "Parameters": {
                "Text": "Hi! We're so happy you called. We'll try to build a list of our top 3 vanity number suggestions generated from the phone number you're calling from."
              },
              "Identifier": "e95d60c0-e95e-4f86-9904-0639dcc39f2b",
              "Type": "MessageParticipant",
              "Transitions": {
                "NextAction": "b1949e38-d7d8-4603-9a76-8090efdfaac1",
                "Errors": [
                  {
                    "NextAction": "b1949e38-d7d8-4603-9a76-8090efdfaac1",
                    "ErrorType": "NoMatchingError"
                  }
                ]
              }
            },
            {
              "Parameters": {
                "SSML": "<say-as interpret-as=\"verbatim\">$.External.message</say-as>\n\n<say-as interpret-as=\"telephone\">$.External.suggestion1</say-as>\n\n<say-as interpret-as=\"telephone\">$.External.suggestion2</say-as>\n\n<say-as interpret-as=\"telephone\">$.External.suggestion3</say-as>"
              },
              "Identifier": "778f9d81-1551-4372-9375-8b88a311b1e3",
              "Type": "MessageParticipant",
              "Transitions": {
                "NextAction": "387a1596-3931-498c-a403-7667fb4cb927",
                "Errors": [
                  {
                    "NextAction": "387a1596-3931-498c-a403-7667fb4cb927",
                    "ErrorType": "NoMatchingError"
                  }
                ]
              }
            },
            {
              "Parameters": {
                "LambdaFunctionARN": "arn:aws:lambda:us-east-1:182796259395:function:ttec-vanity-connect-app-VanityLambda-jwj4B5AxIibW",
                "InvocationTimeLimitSeconds": "3",
                "ResponseValidation": {
                  "ResponseType": "JSON"
                }
              },
              "Identifier": "b1949e38-d7d8-4603-9a76-8090efdfaac1",
              "Type": "InvokeLambdaFunction",
              "Transitions": {
                "NextAction": "778f9d81-1551-4372-9375-8b88a311b1e3",
                "Errors": [
                  {
                    "NextAction": "a26c7a4d-f42f-43b8-a394-8f74c82ba0b1",
                    "ErrorType": "NoMatchingError"
                  }
                ]
              }
            }
          ]
        }
      Description: Inbound call contact flow created by SAM

  ConnectLambdaAssociation:
    Type: AWS::Connect::IntegrationAssociation
    Properties:
      InstanceId: !Ref ConnectInstance
      IntegrationType: LAMBDA_FUNCTION
      IntegrationArn: !GetAtt VanityLambda.Arn

Outputs:
  ConnectInstanceId:
    Description: The Connect Instance ID
    Value: !Ref ConnectInstance

  ConnectInstanceArn:
    Description: The Connect Instance ARN
    Value: !GetAtt ConnectInstance.Arn

  ContactFlowId:
    Description: The Contact Flow ID
    Value: !Ref ConnectContactFlow

  VanityLambdaArn:
    Description: 'ARN of the Vanity Lambda'
    Value: !GetAtt VanityLambda.Arn
